controller_list:
  - name: "arm"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      
  - name: "gripper"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - finger_1_joint
      - finger_2_joint
    
